# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: papermerge

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pycodestyle pytest
        pip install -r requirements/base.txt
        sudo apt install poppler-utils pdftk tesseract-ocr
    - name: Test with pytest
      run: |
        ./run_tests.sh
    - name: Lint with pycodestyle
      run: |
        pycodestyle papermerge --exclude=migrations --count --max-line-length=127 --statistics
